name: Auth Server CI/CD

on:
  push:
    branches: ["main", "Dev"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write # needed for GHCR
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/Web.Api/Dockerfile
          push: true
          tags: ghcr.io/dapplesoft-ad/auth-server:latest

  # deploy-on-server:
  #   runs-on: ubuntu-latest
  #   needs: build-and-push
  #   steps:
  #     - name: Deploy on server via SSH
  #       uses: appleboy/ssh-action@v1.2.0
  #       with:
  #         host: ${{ secrets.SERVER_IP }}
  #         username: ${{ secrets.SERVER_USER }}
  #         key: ${{ secrets.SERVER_SSH_KEY }}
  #         script: |
  #           echo "Starting deployment..."
  #           # Login to GHCR on VPS using PAT
  #           echo "${{ secrets.SERVER_GHCR_PAT }}" | docker login ghcr.io -u "dapplesoft-ad" --password-stdin
  #           echo "Logged in to GitHub Container Registry"
  #           # Navigate to Docker compose directory
  #           cd /home/dapplesoft-ad/apps/docker-composes
  #           # Pull latest image for the auth server service
  #           docker compose -f auth-server.yml pull auth-server
  #           echo "Pulled latest image"
  #           # Recreate the container with the updated image
  #           docker compose -f auth-server.yml up -d --force-recreate auth-server
  #           echo "Recreated container with latest image"
  #           # Clean unused images safely
  #           docker image prune -f || true
  #           echo "Cleaned unused Docker images"
  #           echo "Deployment complete"
